name: Cinnamon Blogger
favicon: null
layout_spectrum: 0.7964954988565296
typography_spectrum: 0.5939469686709344
title: The Cinnamon Blogger
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#130c02'
    - '#67481c'
    - '#d8a355'
    - '#b07532'
  brandStrength: 0.3125
  lightness: 0.14079446764662862
  saturation: 0.7527886296156794
  rhythmicContrast: 0.535201471298933
purpose: []
